# Example snyk script for gitlab pipelines

dependancy_scanning:
  image: node:latest
  stage: test
  script:
    # Install npm, snyk, and snyk-to-html
    - npm install -g npm@latest
    - npm install -g snyk
    - npm install snyk-to-html -g
    # Install JDK, etc
    # - apt install -y openjdk-8-jdk
    - apt-get install -y maven
    - mvn install
    # Run snyk help, snyk auth, snyk monitor, snyk test to break build and out report
    - snyk --help
    - snyk auth $SNYK_TOKEN
    - snyk monitor --all-projects --remote-repo-url=java-goof-gitlab-pipeline
    # - snyk monitor --project-name=java-goof-gitlab-pipeline
    - snyk test --json | snyk-to-html -o snyk_results.html
 
  # Output report
  artifacts:
    when: always
    paths: 
      - snyk_results.html
