---
apiVersion: v1
kind: Service
metadata:
  name: java-goof
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30000 #port exposed on localhost
  selector:
    app: java-goof
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-goof
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: java-goof
  template:
    metadata:
      labels:
        app: java-goof
    spec:
      containers:
      - image: snykschmidtty/java-goof:latest
        name: java-goof
        ports:
        - containerPort: 8080
        resources: {}
        env: 
          - name: "DOCKER"
            value: "1"
      restartPolicy: Always
    
