  version: 2
  jobs:
    build:
      working_directory: ~/java-goof-github-circleci
      docker: 
        - image: circleci/node # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run:
            name: update-npm
            command: 'sudo npm install -g snyk'
        - run:
            name: install-openjdk
            command: 'sudo apt install -y openjdk-8-jdk'
        - run:
            name: install-mvn
            command: 'sudo apt install -y maven'
        - run:
            name: mvn-install
            command: 'mvn install'
        - run: # installs json to html mapper
            name: install-snyk-to-html
            command: 'sudo npm install -g snyk-to-html'
        - run: # run snyk auth - authenticate snyk use environment variables to add token
            name: snyk auth
            command: snyk auth $SNYK_TOKEN
        - run: #run snyk monitor
            name: snyk-monitor-1
            command: 'snyk monitor --all-projects --reachable-vulns --remote-repo-url=java-goof-github-circleci'
        - run: #run snyk monitor
            name: snyk-monitor-2
            command: 'snyk monitor --reachable-vulns --project-name=java-goof-github-circleci --remote-repo-url=java-goof-github-circleci'
        #- run: # output to HTML
        #    name: snyk test to HTML
        #    command: 'snyk test --all-projects --reachable --json | snyk-to-html -o results.html'
        #- store_artifacts:
        #    path: results.html
        #    destination: results.html
