  version: 2
  jobs:
    build:
      working_directory: ~/goof-circleci
      docker: 
        - image: circleci/node # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run:
            name: update-npm
            command: 'sudo npm install -g snyk'
        - run:
            name: install-openjdk
            command: 'sudo apt install -y openjdk-8-jdk'
        - run:
            name: install-mvn
            command: 'sudo apt install -y maven'
        - run:
            name: mvn-install
            command: 'mvn install'
        - run: # installs json to html mapper
            name: install-snyk-to-html
            command: 'sudo npm install -g snyk-to-html'
        - run: # run snyk auth - authenticate snyk use environment variables to add token
            name: snyk auth
            #command: snyk auth d24f029b-f3c4-4adc-853c-12d622ed1faf
            command: snyk auth $SNYK_TOKEN
        - run: # run snyk monitor
            name: snyk monitor
            command: 'snyk monitor --project-name=goof-circleci'
        - run: # output to HTML
            name: snyk test to HTML
            command: 'snyk test --json | snyk-to-html -o results.html'
        - store_artifacts:
            path: results.html
            destination: results.html
