name: GitHub Actions Snyk Scan

on: [push]

jobs:
  #snyk_scan_1:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@master
      #- name: Run Snyk to check for vulnerabilities
        #uses: snyk/actions/maven@master
        #env:
          #SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        #with:
          #command: monitor
          #args: --all-projects --remote-repo-url=java-goof-github #--reachable --project-name=java-goof-github-actions
  snyk_scan_2:
    runs-on: ubuntu-latest
    steps:
      #- name: Setup Java JDK
        #uses: actions/setup-java@v1.4.1
        #with:
          #java-version: 8
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --remote-repo-url=java-goof-github --project-name=java-goof-github-actions # --reachable 
